# Generated by Django 3.1.4 on 2020-12-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='units',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
